#!/usr/bin/env python3
"""Generate a runnable Python validator scaffold from an IR instance (Phase B compiler).

Emits the structural plumbing the corpus proved reusable — score() per signal (a real implementation
from templates/scaffold/metric_library.py when the metric FAMILY resolves, else a clearly-marked
hand-write stub), an aggregator, a smoother (EMA/SMA), a weight-setter, and anti-gaming/burn hooks.
The bespoke judgment (extern leaves) is surfaced as NotImplementedError, never silently wrong.

Scope: the dominant `pipeline` archetype. multiplex/gated/multiplicative emit a best-effort flat
pipeline with a header note; `opaque` emits a stub-only scaffold.

  generate.py <instance.yaml> [-o out.py]      # write a scaffold
  generate.py --check <dir>                    # regeneration test over a dir: every scaffold must
                                               # py_compile AND its embedded signature must match source
"""
from __future__ import annotations

import json
import py_compile
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import imql_core as C  # noqa: E402

try:
    import yaml
except ImportError:
    sys.exit("PyYAML not installed.")

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "templates" / "scaffold"))


def _clean(text: str) -> str:
    """Make text safe to embed inside a Python triple-quoted docstring."""
    return str(text).replace('"""', "'''").replace("\\", "/").replace("\n", " ").strip()


def _ident(name: str) -> str:
    s = "".join(c for c in (name or "Mechanism").replace(" ", "_") if c.isascii() and (c.isalnum() or c == "_"))
    if not s or not s[0].isalpha():
        s = "M_" + s
    return s or "Mechanism"


AGG_BODY = {
    "weighted_average": "    total = sum(w for _, w in scored) or 1.0\n    return {u: s * w / total for u, (s, w) in items(scored)}",
    "softmax": "    import math\n    mx = max((s for s, _ in scored.values()), default=0.0)\n    exps = {u: math.exp((s - mx) / max(temperature or 1.0, 1e-9)) for u, (s, _) in scored.items()}\n    z = sum(exps.values()) or 1.0\n    return {u: e / z for u, e in exps.items()}",
    "proportional": "    total = sum(max(0.0, s) for s, _ in scored.values()) or 1.0\n    return {u: max(0.0, s) / total for u, (s, _) in scored.items()}",
    "winner_take_all": "    if not scored:\n        return {}\n    best = max(scored, key=lambda u: scored[u][0])\n    return {u: (1.0 if u == best else 0.0) for u in scored}",
    "rank_based": "    order = sorted(scored, key=lambda u: scored[u][0], reverse=True)\n    n = len(order) or 1\n    return {u: (n - i) / (n * (n + 1) / 2) for i, u in enumerate(order)}",
}


def generate(ir: dict) -> str:
    from metric_library import FAMILY_IMPL, has_impl  # noqa: E402

    sub = ir.get("subnet") or {}
    name = _ident(sub.get("name"))
    comp = ir.get("composition") or {}
    shape = comp.get("shape") or "pipeline"
    agg = ir.get("aggregation") or {}
    ws = ir.get("weight_setting") or {}
    sm = ws.get("smoothing") or {}
    burn = agg.get("burn_allocation") or {}
    signals = ir.get("scoring_signals") or []
    sig = C.signature(ir)  # embedded for the regeneration check

    L: list[str] = []
    L.append('"""Auto-generated validator scaffold — DO NOT treat as production.')
    L.append(f"Subnet: {sub.get('name')}  (netuid {sub.get('netuid')})  shape={shape}")
    L.append("Generated by tooling/generate.py from the IMQL IR. Fill every NotImplementedError.")
    L.append('"""')
    L.append("import json")
    L.append("import metric_library as M")
    L.append("")
    # machine-readable structural signature (used by --check); stored as JSON for exact fidelity
    L.append("MECHANISM = json.loads(r'''" + json.dumps(_jsonable(sig)) + "''')")
    L.append("")

    if shape != "pipeline":
        L.append(f"# NOTE: source archetype is '{shape}', not 'pipeline'. This scaffold flattens it to a")
        L.append("# single pipeline; multiplex tracks / gating / multiplicative composition need manual wiring.")
        L.append("")

    # --- per-signal score() ---
    for i, s in enumerate(signals):
        if not isinstance(s, dict):
            continue
        fam, spec = C.resolve_metric(s)
        raw = str(s.get("metric_kind_other") or s.get("metric_kind") or "")
        doc = _clean(f"signal: {s.get('name')}  metric={s.get('metric_kind')}"
                     f"{f' family={fam}' if fam else ''}{f' specific={spec}' if spec else ''}  "
                     f"direction={s.get('direction')}")
        L.append(f"def score_{i}(response, ground_truth):")
        L.append(f'    """{doc}"""')
        if s.get("extern") or not has_impl(fam):
            L.append("    raise NotImplementedError(" + repr(f"hand-write the bespoke metric: {raw[:80]}") + ")")
        else:
            fn, contract = FAMILY_IMPL[fam]
            L.append(f"    # canonical primitive — contract: {contract}")
            L.append(f"    # TODO: map (response, ground_truth) to this primitive's inputs")
            L.append(f"    return M.{fn}(response)  # adjust args to: {contract}")
        L.append("")

    # --- aggregate ---
    method = agg.get("method") or "proportional"
    L.append("def aggregate(scored, temperature=%s):" % (agg.get("temperature") if agg.get("temperature") is not None else "None"))
    L.append('    """%s — scored: {uid: (score, weight)} -> {uid: weight}"""' % method)
    L.append("    def items(d):\n        return d.items()")
    L.append(AGG_BODY.get(method, AGG_BODY["proportional"]))
    L.append("")

    # --- smoother ---
    smk = sm.get("kind") or "none"
    L.append("def smooth(prev, new, alpha=%s, window=%s):" % (sm.get("alpha"), sm.get("window")))
    if smk == "ema":
        a = sm.get("alpha") if sm.get("alpha") is not None else 0.1
        L.append(f'    """EMA smoothing (alpha={a})"""')
        L.append(f"    a = alpha if alpha is not None else {a}")
        L.append("    return {u: a * new.get(u, 0.0) + (1 - a) * prev.get(u, 0.0) for u in set(prev) | set(new)}")
    else:
        L.append(f'    """smoothing kind: {smk} (no-op passthrough; wire if needed)"""')
        L.append("    return new")
    L.append("")

    # --- guards + burn (hooks) ---
    guards = ir.get("anti_gaming") or []
    if guards:
        L.append("# anti-gaming guards to enforce (AND-composed):")
        for g in guards:
            if isinstance(g, dict):
                L.append(f"#   - {g.get('kind')} (enforcement: {g.get('enforcement')})")
        L.append("def apply_guards(uid, response):\n    # TODO: enforce the guards above; return False to reject\n    return True")
        L.append("")
    if burn.get("enabled"):
        frac = "dynamic (1 - sum_distributed)" if burn.get("dynamic") else burn.get("fraction")
        L.append(f"BURN_UID = {burn.get('address_or_uid')!r}")
        L.append(f"BURN_FRACTION = {None if burn.get('dynamic') else burn.get('fraction')}  # {frac}")
        L.append("")

    # --- main loop ---
    cadence = ws.get("cadence") or "per_epoch"
    call = ws.get("on_chain_call") or "set_weights"
    L.append("def run_epoch(metagraph, responses, ground_truth, prev_weights):")
    L.append(f'    """cadence: {cadence}  on-chain: {call}  tempo: {ws.get("tempo_or_interval")}"""')
    L.append("    scorers = [%s]" % ", ".join(f"score_{i}" for i in range(len(signals))) if signals else "")
    L.append("    scored = {}")
    L.append("    for uid, resp in responses.items():")
    if guards:
        L.append("        if not apply_guards(uid, resp):\n            continue")
    L.append("        s = sum(f(resp, ground_truth) for f in scorers) / (len(scorers) or 1)")
    L.append("        scored[uid] = (s, 1.0)")
    L.append("    weights = aggregate(scored)")
    L.append("    weights = smooth(prev_weights, weights)")
    if burn.get("enabled"):
        L.append("    # apply burn overlay: route BURN_FRACTION (or residual) to BURN_UID")
    L.append(f"    # {call}(metagraph, weights)")
    L.append("    return weights")
    L.append("")
    return "\n".join(L) + "\n"


def _jsonable(sig: dict):
    def conv(x):
        if isinstance(x, tuple):
            return [conv(v) for v in x]
        if isinstance(x, list):
            return [conv(v) for v in x]
        return x
    return {k: conv(v) for k, v in sig.items()}


def check(target: str) -> int:
    files = sorted(Path(target).rglob("*.yaml"))
    n = ok_compile = ok_sig = 0
    pipeline_n = 0
    fails = []
    for f in files:
        ir = yaml.safe_load(f.read_text())
        if not isinstance(ir, dict):
            continue
        if (ir.get("composition") or {}).get("shape") != "pipeline":
            continue
        pipeline_n += 1
        n += 1
        repo = (ir.get("subnet") or {}).get("owner_repo") or f.stem
        try:
            code = generate(ir)
        except Exception as exc:  # noqa: BLE001
            fails.append((repo, f"generate: {exc}"))
            continue
        with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as tf:
            tf.write(code)
            tmp = tf.name
        try:
            py_compile.compile(tmp, doraise=True)
            ok_compile += 1
        except py_compile.PyCompileError as exc:
            fails.append((repo, f"py_compile: {exc}"))
            continue
        # structural fidelity: embedded MECHANISM signature must equal source signature
        ns: dict = {}
        exec(compile(code, tmp, "exec"), {"metric_library": __import__("metric_library"), "M": __import__("metric_library")}, ns)  # noqa: S102
        emitted = ns.get("MECHANISM")
        src = _jsonable(C.signature(ir))
        if json.dumps(emitted, sort_keys=True) == json.dumps(src, sort_keys=True):
            ok_sig += 1
        else:
            fails.append((repo, "signature drift in scaffold"))
    print(f"regeneration check over {pipeline_n} pipeline subnets: "
          f"py_compile {ok_compile}/{n}, signature-fidelity {ok_sig}/{n}")
    for repo, why in fails[:8]:
        print(f"  FAIL {repo}: {why}")
    return 0 if (ok_compile == n and ok_sig == n) else 1


def main(argv):
    if "--check" in argv:
        t = argv[argv.index("--check") + 1]
        return check(t)
    src = next((a for a in argv if not a.startswith("-")), None)
    if not src:
        print(__doc__)
        return 2
    ir = yaml.safe_load(Path(src).read_text())
    code = generate(ir)
    if "-o" in argv:
        Path(argv[argv.index("-o") + 1]).write_text(code)
    else:
        print(code)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
